### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by jgelens**
Improved and added Dutch translations

### CODE REVIEW

**Comment by kaievns** [comment]
hey! thanks a bunch for quick update!

btw, why did you downcased the month and day names? is that conventional? because everywhere else we use capitalized syntax

**Comment by kaievns** [comment]
okay, I merged it, but I took the liberty of moving the day and month names back to the capitalized format.

i've notified Douwe, the guy who originally wrote the module, if he will agree with your change then we will change it back.

## 

Cheers

**Comment by jgelens** [comment]
In the Dutch language it's normal to downcase them. That's different than the English (and other?) languages.

**Comment by jgelens** [comment]
Checked it with jQuery datepicker, they're also using downcase letters.

**Comment by kaievns** [comment]
in Russian we also use downcased style most of the times, but it is not really against the rules to use capitalized style as well.

personally I don't mind if it will be in lowercase, whatever works the best for you. just trying to have some sort of a collective decision :)

**Comment by jgelens** [comment]
Same for Dutch I think. It's a single word so probably doesn't matter. My coworker also votes for lowercase. Let's see what Douwe replies :)
For me it doesn't matter.

**Comment by kaievns** [comment]
alright, douwe came back to me and voted for the lowcased formatting. so, here you go ac2043c1a9712aa3e22dc1b52b0e035e907e1fd8 :)

**Comment by jgelens** [comment]
great :-D

**Pull request merged**
